services:
  dockerized-dev-environment:
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
        - USER_NAME=${USER_NAME}
    container_name: dockerized-dev-environment
    image: dockerized-dev-environment-image
    tty: true
    stdin_open: true
    command: fish
    user: ${USER_NAME}
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - DISPLAY=${DISPLAY}
    env_file:
      - .env
    volumes:
      - nix:/nix
      - ssh:/home/${USER_NAME}/.ssh
      - local:/home/${USER_NAME}/.local
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}

      - type: bind
        source: ./config/
        target: /home/${USER_NAME}/.config/

      - type: bind
        source: /home/${USER_NAME}/Documents/Programming/
        target: /home/${USER_NAME}/workdir/

      - type: bind
        source: ./config/tmux/.tmux.conf
        target: /home/${USER_NAME}/.tmux.conf

volumes:
  nix:
    name: dockerized-dev-environment-nix
  ssh:
    name: dockerized-dev-environment-ssh
  local:
    name: dockerized-dev-environment-local
