services:
  dockerized-dev-environment:
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
        - USER_NAME=${USER_NAME}
    container_name: dockerized-dev-environment
    image: dockerized-dev-environment-image
    tty: true
    stdin_open: true
    command: fish
    user: ${USER_NAME}
    env_file:
      - .env
    volumes:
      - nix:/nix

      - type: bind
        source: ./config/
        target: /home/${USER_NAME}/.config/

volumes:
  nix:
    name: dockerized-dev-environment-nix
