services:
  dockerized-dev-environment:
    build: .
    image: dockerized-dev-environment
    container_name: dockerized-dev-environment
    tty: true
    volumes:
      - type: bind
        source: ${PWD}
        target: /home/

      - type: bind
        source: ./.config/
        target: /root/.config/

      - type: bind
        source: ${HOST_HOME_DIR}/.ssh/
        target: /root/.ssh/

      - type: bind
        source: ./.gitconfig
        target: /root/.gitconfig

      - type: bind
        source: ./.tool-versions
        target: /root/.tool-versions

      - ./.asdf/:/root/.asdf/

      - ./.local/:/root/.local/
