services:
  dockerized-dev-environment:
    build: .
    image: dockerized-dev-environment
    container_name: dockerized-dev-environment
    tty: true
    deploy:
      resources:
        limits:
          memory: 4.5G
          cpus: "4"
        reservations:
          cpus: "2"
          memory: 2G
    environment:
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
    volumes:
      - type: bind
        source: ${PWD}
        target: /home/

      - type: bind
        source: ./.config/
        target: /root/.config/

      - type: bind
        source: ${HOST_HOME_DIR}/.ssh/
        target: /root/.ssh/

      - type: bind
        source: ./.gitconfig
        target: /root/.gitconfig

      - type: bind
        source: ./.tool-versions
        target: /root/.tool-versions

      - type: bind
        source: ./commitlint.config.js
        target: /root/.local/share/nvim/mason/packages/commitlint/commitlint.config.js

      - ./.asdf/:/root/.asdf/

      - ./.local/:/root/.local/

      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
