services:
  dockerized-dev-environment:
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    image: dockerized-dev-environment
    container_name: dockerized-dev-environment
    tty: true
    deploy:
      resources:
        limits:
          memory: 4.5G
        reservations:
          cpus: "2"
          memory: 2G
    environment:
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      DISPLAY: ${DISPLAY}
    volumes:
      - type: bind
        source: ${PWD}
        target: /home/${USER_NAME}/workdir/

      - type: bind
        source: ./.config/
        target: /home/${USER_NAME}/.config/

      - type: bind
        source: ${HOST_HOME_DIR}/.ssh/
        target: /home/${USER_NAME}/.ssh/

      - type: bind
        source: ./.gitconfig
        target: /home/${USER_NAME}/.gitconfig

      - type: bind
        source: ./.tool-versions
        target: /home/${USER_NAME}/.tool-versions

      - ./.asdf/:/home/${USER_NAME}/.asdf/

      - ./.local/:/home/${USER_NAME}/.local/

      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}

      - /tmp/.X11-unix:/tmp/.X11-unix
